### ISSUE TITLE
codeception/codeception 5.x support

### ISSUE THREAD

**Issue by 99hops** [Codeception/module-redis#13]
Please add Codeception 5.x support 

`codeception/module-redis[1.0.1, ..., 1.3.0] require codeception/codeception ^4.0 -> found codeception/codeception[4.0.0, ..., 4.1.x-dev] but it conflicts with your root composer.json require (5.0.x-dev)`

**Comment by Naktibalda** [comment]
Any reason to use unfinished 5.0 branch?

**Comment by 99hops** [comment]
Yes, I actually have it's related to [Symfony 6](https://github.com/Codeception/Codeception/pull/6273)

**Comment by Naktibalda** [comment]
Released as 3.0.0
