### ISSUE TITLE
predis/predis 2.x dependency

### ISSUE THREAD

**Issue by AlexOstrovsky** [Codeception/module-redis#17]
Please add predis 2.x support

Problem 1
    - Root composer.json requires snc/redis-bundle 4.5.0 -> satisfiable by snc/redis-bundle[4.5.0].
    - codeception/module-redis 3.0.0 requires predis/predis ^1.1 -> satisfiable by predis/predis[v1.1.0, ..., v1.1.x-dev].
    - snc/redis-bundle 4.5.0 conflicts with predis/predis v1.1.10.
    - snc/redis-bundle 4.5.0 conflicts with predis/predis v1.1.2.
    - Root composer.json requires codeception/module-redis 3.0.0 -> satisfiable by codeception/module-redis[3.0.0].

**Comment by Naktibalda** [comment]
Released as 3.1.0, please let me know if you have any issues with it.
